# Generated by Django 4.1.6 on 2025-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_added_on_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='added_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
