# Generated by Django 4.1.6 on 2025-03-19 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
