# Generated by Django 4.1.6 on 2025-03-19 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
