# Generated by Django 4.1.6 on 2025-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='added_on',
            field=models.DateField(default='2003-02-02'),
        ),
    ]
