# Generated by Django 4.1.6 on 2025-03-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_on',
        ),
    ]
