[phases.setup]
apt = ["python3.8", "postgresql-16", "gcc"]

[phases.install]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
commands = ["yarn run build"]

[phases.start]
commands = ["python manage.py migrate", "gunicorn gradebook.wsgi"]