[phases.setup]
nixPkgs = ['...','gcc','postgresql_16.dev','python38', 'python38Packages.pip']

[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn gradebook.wsgi --log-file -"
