# Generated by Django 4.1.6 on 2023-06-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subjectperclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_open', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_closed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.session')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.term')),
            ],
        ),
    ]
