# Generated by Django 4.1.6 on 2023-06-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentprofile_resumptionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_admitted',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='session_admitted',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='core.session'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='term_admitted',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='core.term'),
        ),
    ]
