# Generated by Django 4.1.6 on 2023-06-29 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachersubjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
