# Generated by Django 4.1.6 on 2023-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
