# Generated by Django 4.1.6 on 2023-07-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_classteacher_status_alter_subjectteacher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstscore', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('secondscore', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('thirdscore', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('totalca', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('examscore', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subjecttotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subjaverage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subjectposition', models.IntegerField(null=True)),
                ('subjectgrade', models.CharField(max_length=10, null=True)),
                ('subjectrating', models.CharField(max_length=10, null=True)),
                ('highest_inclass', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('lowest_inclass', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.session')),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subject')),
                ('subjectteacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.subjectteacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
