# Generated by Django 4.1.6 on 2023-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
