# Generated by Django 4.1.6 on 2023-07-03 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_studentaffective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formmaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentaffective',
            name='affective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affective'),
        ),
        migrations.AlterField(
            model_name='studentaffective',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rating'),
        ),
        migrations.AlterField(
            model_name='studentaffective',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachersubjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
