# Generated by Django 4.1.6 on 2023-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_scores_firstscore_alter_scores_subjaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='subjaverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
