# Generated by Django 4.1.6 on 2023-07-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_scores_subjaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(null=True)),
                ('status', models.CharField(default='No', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
