# Generated by Django 4.1.6 on 2023-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_admissionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_numberstring',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
