# Generated by Django 4.1.6 on 2025-07-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_studentprofile_admission_numberstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scores_sessions', to='core.session'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='studentclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scores_class', to='core.schoolclass'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scores_subjects', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='subjectteacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scores_teacher', to='core.subjectteacher'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scores_terms', to='core.term'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classrooms', to='core.schoolclass'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='core.session'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='core.subject'),
        ),
    ]
